# Configuration of Hugo
# Guide: https://wowchemy.com/docs/getting-started/
# Hugo Documentation: https://gohugo.io/getting-started/configuration/#all-configuration-settings
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/


title: 'CMC Corpora'
# Website URL. End your URL with a `/` trailing slash, e.g. `https://example.com/`.
baseurl: '/'
# canonifyurls: true  # relevant for gitlab.com deployment?
# Footer text, e.g. 'Â© {year} Me'
copyright: ''

############################
## LANGUAGE
############################

defaultContentLanguage: en
hasCJKLanguage: false
defaultContentLanguageInSubdir: false
removePathAccents: true

############################
## MODULES
############################

module:
  imports:
    - path: github.com/wowchemy/wowchemy-hugo-modules/wowchemy-cms/v5
    - path: github.com/wowchemy/wowchemy-hugo-modules/wowchemy/v5

############################
## ADVANCED
############################

enableGitInfo: true  # Get last modified date for content from Git?
summaryLength: 30
paginate: 7
enableEmoji: true
enableRobotsTXT: true
footnotereturnlinkcontents: <sup>^</sup>
ignoreFiles: [\.ipynb$, .ipynb_checkpoints$, \.Rmd$, \.Rmarkdown$, _cache$, \.sw.$]

permalinks:
  # tags: '/tag/:slug/'
  # categories: '/category/:slug/'
  # publication_types: '/publication-type/:slug/'
  authors: '/people/:slug/'
  project: '/conferences/:filename/'  # needed for 'project' links to point to '/conferences'
  publication: '/publications/:filename/'
  post: '/posts/:year-:month-:slug/'
  event: "/events/:year/:slug/"

# Disable aliases when `redirects` is added to the `outputs` below. (netlify specific)
disableAliases: false

outputs:
  home: [HTML, RSS, JSON, WebAppManifest, headers, redirects]
  section: [HTML, RSS]

imaging:
  resampleFilter: lanczos
  quality: 75
  anchor: smart

security:
  funcs:
    getenv:
      - ^HUGO_
      - ^WC_

timeout: 600000

taxonomies:
  tag: tags
  category: categories
  publication_type: publication_types # needed for publication/ type search
  author: authors # needed for ckcmc/partners authors

markup:
  _merge: deep
  defaultMarkdownHandler: "goldmark"
  goldmark:
    renderer:
      unsafe: true
    highlight:
      codeFences: false
    tableOfContents:
      startLevel: 2
      endLevel: 3

related:
  threshold: 80
  includeNewer: true
  toLower: true
  indices:
    - name: tags
      weight: 100
    - name: categories
      weight: 70
    - name: title
      weight: 60
    - name: summary
      weight: 50
    - name: authors
      weight: 20
    - name: publication_types
      weight: 50
