# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: 'Conference Series'
    weight: 10
    url: 'series/'

  - name: 'Series Overview'
    url: 'series/#'
    parent: 'Conference Series'
    weight: 10
  - name: 'Committee'
    url: 'series/#committee'
    parent: 'Conference Series'
    weight: 20
  - name: 'Conferences'
    url: 'series/#conferences'
    parent: 'Conference Series'
    weight: 30
  - name: 'Proceedings'
    url: 'series/#proceedings'
    parent: 'Conference Series'
    weight: 40
  - name: 'Organization'
    url: 'series/#orga'
    parent: 'Conference Series'
    weight: 50


  - name: 'CLARIN K-centre for CMC'
    weight: 20
  - name: 'CKCMC Overview'
    url: 'ckcmc/#'
    parent: 'CLARIN K-centre for CMC'
    weight: 10
  - name: 'Partners'
    url: 'ckcmc/#partners'
    parent: 'CLARIN K-centre for CMC'
    weight: 20
  - name: 'Contact the CKCMC'
    url: 'ckcmc/#contact'
    parent: 'CLARIN K-centre for CMC'
    weight: 30
  - name: 'Events'
    url: 'events/'
    parent: 'CLARIN K-centre for CMC'
    weight: 40
  - name: 'Forum'
    url: 'https://forum.clarin.eu/c/ckcmc/'
    parent: 'CLARIN K-centre for CMC'
    weight: 50
  - name: 'Documentation'
    url: 'ckcmc/docs/'
    parent: 'CLARIN K-centre for CMC'
    weight: 60


  - name: 'CMC-TEI'
    url: 'ckcmc/docs/tei/'
    weight: 30


  - name: 'Publications'
    url: 'publications/'
    weight: 40


  - name: 'News'
    url: 'posts/'
    weight: 50

  - name: 'Contact'
    url: '#contact'
    weight: 60

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/uploads/resume.pdf` and uncomment the lines below.
#  - name: CV
#    url: uploads/resume.pdf
#    weight: 70
