# SITE SETUP
# Guide: https://wowchemy.com/docs/getting-started/
# Documentation: https://wowchemy.com/docs/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance

# Choose a theme.
theme: ocean
# Enable users to switch between day and night mode?
day_night: false
# Override the theme's font set (optional).
#   Latest font sets (may require updating): https://sourcethemes.com/academic/themes/
#   Browse built-in font sets in `themes/academic/data/fonts/`
#   Browse user installed font sets in `data/fonts/`
font: 'ckcmc'
# Choose a font size.
# Sizes: XS (extra small), S (small), M (medium), L (large - DEFAULT), XL (extra large)
font_size: M

# SEO

site_type: 'Project'
local_business_type: ''
org_name: ''
description: 'CMC Corpora Web Site'
twitter: 'cmc_corpora'

# Contact (edit or remove options as required)

email: contact@cmc-corpora.org
# phone: ''
# address:
#   street: ''
#   city: ''
#   region: ''
#   postcode: ''
#   country: ''
#   country_code: ''
# coordinates:
#   latitude: ''
#   longitude: ''
# directions: ''
# office_hours:
#   - ''
# appointment_url: ''
contact_links:
  - icon: twitter
    icon_pack: fab
    name: twitter
    link: 'https://twitter.com/cmc_corpora'
    label: Follow me on Twitter
    display:
      header: true
  - icon: facebook
    icon_pack: fab
    name: facebook
    link: 'https://www.facebook.com/cmccorpora'
  - icon: google
    icon_pack: fab
    name: google Group
    link: 'https://groups.google.com/forum/?hl=de#!forum/cmc-corpora'

# Site header

main_menu:
  enable: true
  align: l
  show_logo: true
  show_language: false
  show_day_night: false
  show_search: true
  highlight_active_link: false

# Localization

date_format: '02 Jan 2006'
time_format: '15:04'
address_format: en-gb

# Site features

highlight: true
highlight_languages:
  - r
  - latex
math: false
diagram: false
privacy_pack: true
edit_page:
  # repo_url: 'https://gitlab.com/ckcmc/ckcmc.gitlab.io.git'
  repo_url: ''
  content_dir: ''
  repo_branch: master
  editable:
    page: true
    post: true
    book: true
show_related:
  book: true
  page: false
  post: true
  project: true
  publication: true
  event: true
reading_time: false
section_pager: false
docs_section_pager: true
sharing: true
copyright_license:
  enable: true
  allow_derivatives: true
  share_alike: false
  allow_commercial: true
  notice: 'This work is licensed under {license}'
abstract_length: 135
plugins_js: []
avatar:
  gravatar: false
  shape: circle
publications:
  date_format: 'January 2006'
  citation_style: apa
projects:
  # Views for associated content.
  #   1: List
  #   2: Compact
  #   3: Card
  #   4: Citation (publications only)
  post_view: 2
  publication_view: 2
  talk_view: 2
breadcrumb:
  page_types:
    book: true
comments:
  provider: ''
  commentable:
    post: true
    book: true
    project: true
    publication: true
    event: true
  disqus:
    shortname: ''
    show_count: true
  commento:
    url: ''
search:
  provider: wowchemy
  algolia:
    app_id: ''
    api_key: ''
    index_name: ''
    show_logo: false
map:
  provider: ''
  api_key: ''
  zoom: 15
marketing:
  google_analytics: ''
  google_tag_manager: ''
  google_site_verification: ''
  baidu_site_verification: ''
  baidu_tongji: ''
cms:
  branch: master
  local_backend: false
icon:
  pack:
    ai: false

# authors:
#   RelPermalink: false
