backend:
  name: gitlab
  repo: ckcmc/ckcmc.gitlab.io
  auth_type: implicit
  app_id: ed1d9ac4ce9d273baea1dbdc7410c6143fa97af11df5a9be6177ef74524eb0b9
publish_mode: 'editorial_workflow'
media_folder: 'static/media/'
public_folder: 'media'
collections:
  - name: authors
    label: People
    folder: 'content/authors'
    path: '{{slug}}/_index'
    create: true  # Allow users to create new documents in this collection
    fields:  # The fields each document in this collection have
      - {label: "Display name (such as your full name)", name: "title", widget: "string"}
      - label: "Picture"
        hint: "An image named `avatar.jpg/png` will automatically be shown on the page"
        name: "avatar_filename"
        widget: "image"
        default: "avatar"
        required: false
        media_library:
          config:
            multiple: false
      - label: "Short summary"
        hint: "Shown in author boxes"
        name: "bio"
        widget: "string"
        required: false
      - label: "Full biography"
        hint: "Shown on author pages"
        name: "body"
        widget: "markdown"
        required: false
      - label: "Interests"
        hint: "Shown on author pages"
        name: "interests"
        required: false
        widget: "list"
        pattern: ['[a-zA-Z -_]', "Characters, spaces, hyphens, and underscores"]
      - label: "Organizations you belong to or are affiliated with"
        hint: "Shown on author pages"
        name: "organizations"
        required: false
        widget: "list"
        fields:
          - {label: Organization, name: name, widget: string, required: true}
          - {label: Link, name: url, widget: string, required: false}
      - label: "Email"
        hint: "Currently, for internal use only"
        name: "email"
        widget: "string"
        required: true
      - label: "Super user"
        name: "superuser"
        widget: "hidden"
        default: false
      - label: "User groups"
        hint: "'steering committee', 'former steering committee', 'CKCMC', ..."
        name: "user_groups"
        required: false
        widget: "list"
      - label: "Committee period (if applicable)"
        hint: "'2014 - 2015' or 'since 2015'"
        name: "committee_period"
        widget: "string"
        required: false
  - name: posts
    label: Posts
    label_singular: Post
    folder: 'content/post'
    path: '{{slug}}/index'
    create: true  # Allow users to create new documents in this collection
    fields:  # The fields each document in this collection have
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Subtitle", name: "subtitle", widget: "string", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Publish this page on", name: "date", widget: "datetime"}
      - {label: "Summary", name: "summary", widget: "markdown", required: false}
      - label: "Draft"
        name: "draft"
        widget: "boolean"
        default: false
      - label: "Featured"
        name: "featured"
        widget: "boolean"
        default: false
      - label: "Authors"
        name: "authors"
        required: false
        widget: "list"
      - label: "Tags"
        name: "tags"
        required: false
        widget: "list"
      - label: "Categories"
        name: "categories"
        required: false
        widget: "list"
      - label: "Conferences"
        name: "projects"
        required: false
        widget: "list"
      - label: "Featured Image"
        name: "image"
        required: false
        widget: object
        fields:
          - label: "Upload an image named `featured.jpg/png`"
            name: "filename"
            widget: "image"
            default: "featured"
            media_library:
              config:
                multiple: false
          - {label: Caption, name: caption, widget: string, required: false}
          - {label: Description for screen readers, name: alt_text, widget: string, required: false}
          - {label: "Where's the focal point in the image? Smart, Center, TopLeft, Top, TopRight, Left, Right, BottomLeft, Bottom, BottomRight.", name: focal_point, widget: string, required: false, default: "Smart"}
          - {label: Thumbnail Only?, name: preview_only, widget: boolean, default: false}
  - name: projects
    label: Conferences
    label_singular: Conference
    folder: 'content/project'
    path: '{{slug}}/index'
    create: true  # Allow users to create new documents in this collection
    fields:  # The fields each document in this collection have
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Subtitle", name: "subtitle", widget: "string", required: false}
      - {label: "Body", name: "body", widget: "markdown", required: false}
      - {label: "Publish this page on", name: "date", widget: "datetime"}
      - {label: "Summary", name: "summary", widget: "markdown", required: false}
      - label: "Draft"
        name: "draft"
        widget: "boolean"
        default: false
      - label: "Featured"
        name: "featured"
        widget: "boolean"
        default: false
      - label: "Authors"
        name: "authors"
        required: false
        widget: "list"
      - label: "Tags"
        name: "tags"
        required: false
        widget: "list"
      - label: "Categories"
        name: "categories"
        required: false
        widget: "list"
      - {label: "External link (optional - replaces link to project page)", name: "external_link", widget: "string"}
      - label: Links
        name: links
        required: false
        widget: list
        fields:
          - {label: Link, name: url, widget: string}
          - {label: Link text, name: name, widget: string, required: false}
          - label: Icon pack
            name: icon_pack
            widget: select
            multiple: false
            required: false
            options:
              - {label: "None", value: ""}
              - {label: "Solid", value: "fas"}
              - {label: "Regular", value: "far"}
              - {label: "Brand", value: "fab"}
              - {label: "Academic", value: "ai"}
          - {label: "Icon (see https://sourcethemes.com/academic/docs/page-builder/#icons)", name: icon, widget: string, required: false}
      - label: "Featured Image"
        name: "image"
        required: false
        widget: object
        fields:
          - label: "Upload an image named `featured.jpg/png`"
            name: "filename"
            widget: "image"
            default: "featured"
            media_library:
              config:
                multiple: false
          - {label: Caption, name: caption, widget: string, required: false}
          - {label: Description for screen readers, name: alt_text, widget: string, required: false}
          - {label: "Where's the focal point in the image? Smart, Center, TopLeft, Top, TopRight, Left, Right, BottomLeft, Bottom, BottomRight.", name: focal_point, widget: string, required: false, default: "Smart"}
          - {label: Thumbnail Only?, name: preview_only, widget: boolean, default: false}
  - name: publications
    label: Publications
    label_singular: Publication
    folder: 'content/publication'
    path: '{{slug}}/index'
    create: true  # Allow users to create new documents in this collection
    format: 'yaml-frontmatter'
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Subtitle", name: "subtitle", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "string"}
      - {label: "Abstract", name: "abstract", widget: "markdown"}
  - name: pages
    label: "Pages"
    files:
      - file: "content/privacy.md"
        label: "Privacy Policy"
        name: "privacy"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Publish Date", name: "date", widget: "datetime"}
          - {label: "Subtitle", name: "subtitle", widget: "string", required: false}
          - {label: "Summary", name: "summary", widget: "markdown", required: false}
          - label: "Draft"
            name: "draft"
            required: false
            widget: "boolean"
            default: false
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "content/terms.md"
        label: "Terms"
        name: "terms"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Publish Date", name: "date", widget: "datetime"}
          - {label: "Subtitle", name: "subtitle", widget: "string", required: false}
          - {label: "Summary", name: "summary", widget: "markdown", required: false}
          - label: "Draft"
            name: "draft"
            required: false
            widget: "boolean"
            default: false
          - {label: "Body", name: "body", widget: "markdown"}
